library(moments)
library(haven)
library(xts)
library("dplyr")
library(fitdistrplus)
library(logspline)#install.packages("ggplot2")
library(ggplot2)
library(forecast)
source("w1/pr.R")
stats<-function(ts){
    m=mean(ts); sd<-sd(ts); ku<-kurtosis(ts); sk<-skewness(ts)
    pr("mean: %f, sd: %f, kurtosis: %f, skewness %f",m,sd,ku,sk)
}
filename<-"w1/week 4 data.dta"; path<-file.path(filename); df <- read_dta(path)
ts<-xts(x=df$sp500,order.by = df$date)
head(ts,n=3)
stats(ts)
plot(ts)
qqnorm(ts, pch = 1, frame = FALSE)
qqline(ts, col = "steelblue", lwd = 2)
returns<-diff(ts)/lag(ts)*100
stats(returns)
head(returns,n=3)
returns<-returns[-1,] # remove first
head(returns,n=3)
plot(returns)
qqnorm(returns, pch = 1, frame = FALSE)
qqline(returns, col = "steelblue", lwd = 2)
# check abs and ^2
library("ggpubr")
ggdensity(returns,main = "density",xlab = "% return")
#curve(dnorm(x, 0, 1), from=-4, to=4)
stats(returns)
m=mean(returns)
sd=sd(returns)
x0<-m-4*sd; x1<-m+4*sd
x0=-20; x1=20
print(x0)
print(x1)
#curve(dnorm(x, m, sd), from=x0, to=x1, bty="n", xlab="")
curve(dnorm(x, m, sd), xlim=c(x0,x1), bty="n", xlab="")
fit <- auto.arima(returns)
#shapiro.test(pr$sp500)
#descdist(ts$sp500, discrete = FALSE)
